title: System Design Hub
description: A comprehensive guide to system design - from junior to distinguished engineer
theme: just-the-docs

url: https://AshutoshanandSinha.github.io
baseurl: /system-design-hub

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/AshutoshanandSinha/system-design-hub"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2025. System Design Hub - A comprehensive resource for learning system design."

# Color scheme
color_scheme: custom

# Enable copy button on code blocks
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Navigation settings
nav_sort: case_insensitive
